Added Logo1 #61
Feminine-Divine/Woodog pull request #73
Opened 2021-06-17 17:38 UTC by ishitakapoor26

Fixes #61 

## Checklist:

- [ ] Have you checked there aren't other open [Pull Requests](https://github.com/Feminine-Divine/Woodog/pulls) for the same update/change?
- [ ] Your submission doesn't break any existing feature.
- [ ] Have you tested the code before submission?

---

2021-06-17 17:38 UTC, ishitakapoor26 commented
@hariramjp777 pls review pr.

2021-06-17 19:02 UTC, khushishikhu approved these changes

2021-06-18 04:17 UTC, Aaishpra commented
Can you add a screenshot for the change @ishitakapoor26 then it will be easier for us to review.

2021-06-18 07:55 UTC, hariramjp777 requested changes

2021-06-18 07:55 UTC, hariramjp777 commented on Woodog/templates/partials/base.html
> +    <a class="navbar-brand logo" href="#"><img src="{% static 'img/woodog-logo1.png' %}"></a>
Hi @ishitakapoor26, Thanks for your contribution.
Can you please remove the background of the logo? It'll be good if we just have the icon and the text 'Woodog'.

2021-06-18 07:56 UTC, hariramjp777 commented on Woodog/templates/partials/base.html
> +    <a class="navbar-brand logo" href="#"><img src="{% static 'img/woodog-logo1.png' %}"></a>
![image](https://user-images.githubusercontent.com/58631762/122527223-c2360c00-d038-11eb-821a-3e3018729172.png)

Here's the screenshot,

2021-06-18 07:58 UTC, hariramjp777 commented on Woodog/templates/partials/base.html
> +    <a class="navbar-brand logo" href="#"><img src="{% static 'img/woodog-logo1.png' %}"></a>
Also, Add `style` attribute for `<img>` to give width.

```html
<img src="/static/img/woodog-logo1.png" style="width: 80px;">
```

2021-06-18 08:19 UTC, hariramjp777 approved these changes

2021-06-18 08:19 UTC, hariramjp777 commented on Woodog/templates/partials/base.html
> +    <a class="navbar-brand logo" href="#"><img src="{% static 'img/woodog-logo1.png' %}" style="width: 80px;"></a>
:+1:

2021-06-18 08:28 UTC, merged