created contributing.md file
Feminine-Divine/Woodog pull request #8
Opened 2021-06-10 15:00 UTC by coding-geek21

## What do these changes do?
created contributing.md file

## Related Issue

Fixes #6 

## Checklist:

- [x] Have you checked there aren't other open [Pull Requests](https://github.com/Feminine-Divine/Woodog/pulls) for the same update/change?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video or GIF:

![image](https://user-images.githubusercontent.com/53329034/121548550-bb047200-ca2a-11eb-9bd8-427287dc1a54.png)

---

2021-06-10 15:04 UTC, hariramjp777 approved these changes

2021-06-11 02:07 UTC, Aaishpra requested changes
Thanks for this, can you also write a line in the readme to mention this file there, something like "please don't forget to follow contributing guidelines' and link this file.

2021-06-11 06:27 UTC, coding-geek21 commented
> Thanks for this, can you also write a line in the readme to mention this file there, something like "please don't forget to follow contributing guidelines' and link this file.

Done :)

2021-06-11 06:30 UTC, hariramjp777 approved these changes
Please merge this @Aaishpra

2021-06-11 06:30 UTC, hariramjp777 commented on README.md
> +* Please take a moment to review the [Code of Conduct](https://github.com/Feminine-Divine/Woodog/blob/master/CODE_OF_CONDUCT.md) and [contributing.md](https://github.com/Feminine-Divine/Woodog/blob/m
Okay :+1:

2021-06-11 07:18 UTC, Aaishpra approved these changes
Lgtm

2021-06-11 07:18 UTC, merged