After Login login/signup will be replaces by username
Feminine-Divine/Woodog pull request #85
Opened 2021-06-21 11:38 UTC by 7saikat7

## What do these changes do?

After User has successfully  logged in , His/Her username will be shown in the top of the page and the signup and login buttons will be replaced  which is creating mass confusion to user that they are logged in or not !

## Related Issue

Fixes #

## Checklist:

- [ ] Have you checked there aren't other open [Pull Requests](https://github.com/Feminine-Divine/Woodog/pulls) for the same update/change?
- [ ] Your submission doesn't break any existing feature.
- [ ] Have you tested the code before submission?

## Screenshots or Video or GIF:

---

2021-06-21 12:56 UTC, khushishikhu commented
@7saikat7 please first open the issue, get assigned on it by asking us, and then make a PR

2021-06-21 13:36 UTC, 7saikat7 commented
Ok sure !

2021-06-21 16:16 UTC, khushishikhu requested changes

2021-06-21 16:16 UTC, khushishikhu commented on Woodog/templates/partials/base.html
> +       <a class="btn" id="login-navbtn" type="button" href="{% url 'appdashboard' %}">welcome  {{user.username}} !</a>
```suggestion
       <a class="btn" id="login-navbtn" type="button" href="{% url 'appdashboard' %}">Welcome  to woodog {{user.username}} !</a>
```

2021-06-21 16:18 UTC, khushishikhu commented
Requested some changes. Also solve the merge conflict so that I can merge this

2021-06-22 11:12 UTC, khushishikhu approved these changes

2021-06-22 11:12 UTC, merged